import RubiksCube
import MovementCube

cube = RubiksCube.RubiksCube()
mc = MovementCube.Movement()
print("#########################################")
print(cube.getTab())
print("#########################################")
mc.right(cube)
print(cube.getTab())
print("#########################################")
mc.left(cube)
print(cube.getTab())
print("#########################################")
mc.up(cube)
print(cube.getTab())
print("#########################################")
mc.invUp(cube)
print(cube.getTab())
print("#########################################")
mc.invLeft(cube)
print(cube.getTab())
print("#########################################")
mc.invRight(cube)
print(cube.getTab())
print("#########################################")
