import Movement
import RubiksCube

cube = RubiksCube.RubiksCube()
move = Movement.Movement()
move.fin()
move.initialisation()
print(cube.getTab())
print()
print()
move.x(cube)
print(cube.getTab())
print()
print()
move.invX(cube)
print(cube.getTab())
print()
print()
move.invY(cube)
print(cube.getTab())
print()
print()
move.y(cube)
print(cube.getTab())
print()
print()
move.fin()